#!/bin/bash

# Script to generate version information with auto-incrementing build number
# Usage: ./generate_version.sh

VERSION_FILE="src/core/version.h"
BUILD_FILE=".build_number"

# Version information
MAJOR_VERSION=0
MINOR_VERSION=0
PATCH_VERSION=1

# Read current build number or start at 1
if [ -f "$BUILD_FILE" ]; then
    BUILD_NUMBER=$(cat "$BUILD_FILE")
else
    BUILD_NUMBER=0
fi

# Increment build number
BUILD_NUMBER=$((BUILD_NUMBER + 1))

# Save new build number
echo "$BUILD_NUMBER" > "$BUILD_FILE"

# Get current date and time
BUILD_DATE=$(date '+%Y-%m-%d')
BUILD_TIME=$(date '+%H:%M:%S')
BUILD_TIMESTAMP=$(date '+%Y%m%d%H%M%S')

# Generate version header file
cat > "$VERSION_FILE" << EOF
#ifndef VERSION_H
#define VERSION_H

// Auto-generated version information
// Do not edit this file manually

#define VERSION_MAJOR $MAJOR_VERSION
#define VERSION_MINOR $MINOR_VERSION
#define VERSION_PATCH $PATCH_VERSION
#define VERSION_BUILD $BUILD_NUMBER

#define VERSION_STRING "$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION"
#define VERSION_FULL_STRING "$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION-build$BUILD_NUMBER"

#define BUILD_DATE "$BUILD_DATE"
#define BUILD_TIME "$BUILD_TIME"
#define BUILD_TIMESTAMP "$BUILD_TIMESTAMP"

#define VERSION_INFO_STRING "v$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION ($BUILD_NUMBER) built on $BUILD_DATE $BUILD_TIME"

#endif // VERSION_H
EOF

echo "Generated version $MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION-build$BUILD_NUMBER"
echo "Built: $BUILD_DATE $BUILD_TIME" 
