#ifndef VERSION_H
#define VERSION_H

// Auto-generated version information
// Do not edit this file manually

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_PATCH 1
#define VERSION_BUILD 21

#define VERSION_STRING "0.0.1"
#define VERSION_FULL_STRING "0.0.1-build21"

#define BUILD_DATE "2025-07-04"
#define BUILD_TIME "20:17:02"
#define BUILD_TIMESTAMP "20250704201702"

#define VERSION_INFO_STRING "v0.0.1 (21) built on 2025-07-04 20:17:02"

#endif // VERSION_H
