#ifndef VERSION_H
#define VERSION_H

// Auto-generated version information
// Do not edit this file manually

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_PATCH 1
#define VERSION_BUILD 14

#define VERSION_STRING "0.0.1"
#define VERSION_FULL_STRING "0.0.1-build14"

#define BUILD_DATE "2025-07-02"
#define BUILD_TIME "21:44:39"
#define BUILD_TIMESTAMP "20250702214439"

#define VERSION_INFO_STRING "v0.0.1 (14) built on 2025-07-02 21:44:39"

#endif // VERSION_H
